# Exercícios:

- Utilize o dataset contido nesse [link](https://www.kaggle.com/datasets/upadorprofzs/testes), e responda as questões abaixo.

- O dataset contém dados estatísticos do IBGE relativos à escolaridade, renda, entre outros campos avaliados pela  PNAD (Pesquisa Nacional por Amostra de Domicílios).

- Os dados podem representar informações relevantes e reveladoras sobre a distribuição de renda e possivelmente alguns indicadores sobre tais situações encontradas a partir dos dados.

In [3]:
import pandas as pd
import numpy as np

df_ibge = pd.read_csv('dados_ibge.csv')

df_ibge.head()


UF  Sexo  Idade  Cor  Anos de Estudo  Renda    Altura
0  11     0     23    8              12    800  1.603808
1  11     1     23    2              12   1150  1.739790
2  11     1     35    8              15    880  1.760444
3  11     0     46    2               6   3500  1.783158
4  11     1     47    8               9    150  1.690631

In [4]:
df_ibge.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76840 entries, 0 to 76839
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   UF              76840 non-null  int64  
 1   Sexo            76840 non-null  int64  
 2   Idade           76840 non-null  int64  
 3   Cor             76840 non-null  int64  
 4   Anos de Estudo  76840 non-null  int64  
 5   Renda           76840 non-null  int64  
 6   Altura          76840 non-null  float64
dtypes: float64(1), int64(6)
memory usage: 4.1 MB


1) Qual a quantidade de pessoas nas seguintes faixas etárias:
- 20 Anos ou Menos
- 21 a 35 Anos
- 36 a 50 Anos
- 51 a 65 Anos
- Maiores de 65 Anos



In [5]:
bins = [0, 20, 35, 50, 65, np.inf]
labels = ['20 Anos ou Menos', '21 a 35 Anos', '36 a 50 Anos', '51 a 65 Anos', 'Mais de 65 Anos']

df_ibge['Faixa Etária'] = pd.cut(df_ibge['Idade'], bins=bins, labels=labels)

df_quantidade_de_pessoas_por_faixas_etarias = df_ibge['Faixa Etária'].value_counts().sort_index().reset_index()

df_quantidade_de_pessoas_por_faixas_etarias.columns = ['Faixa Etária', 'Quantidade de Pessoas']

df_quantidade_de_pessoas_por_faixas_etarias


Faixa Etária  Quantidade de Pessoas
0  20 Anos ou Menos                    764
1      21 a 35 Anos                  20654
2      36 a 50 Anos                  31770
3      51 a 65 Anos                  20006
4   Mais de 65 Anos                   3646

2) Qual é a média de escolaridade em cada faixa etária?

In [6]:
df_ibge.head()


UF  Sexo  Idade  Cor  Anos de Estudo  Renda    Altura  Faixa Etária
0  11     0     23    8              12    800  1.603808  21 a 35 Anos
1  11     1     23    2              12   1150  1.739790  21 a 35 Anos
2  11     1     35    8              15    880  1.760444  21 a 35 Anos
3  11     0     46    2               6   3500  1.783158  36 a 50 Anos
4  11     1     47    8               9    150  1.690631  36 a 50 Anos

In [7]:
df_ibge['Anos de Estudo'].unique()


array([12, 15,  6,  9, 14, 16, 10,  1,  5,  7,  3,  2,  4,  8, 11, 17, 13],
      dtype=int64)

In [8]:
df_ibge['Anos de Estudo'] = df_ibge['Anos de Estudo'].map({
    1: 0,
    2: 1,
    3: 2,
    4: 3,
    5: 4,
    6: 5,
    7: 6,
    8: 7,
    9: 8,
    10: 9,
    11: 10,
    12: 11,
    13: 12,
    14: 13,
    15: 14,
    16: 15,
    17: 17
})

df_ibge['Anos de Estudo'].unique()


array([11, 14,  5,  8, 13, 15,  9,  0,  4,  6,  2,  1,  3,  7, 10, 17, 12],
      dtype=int64)

In [9]:
df_sem_registros_de_anos_nao_determinados = df_ibge[df_ibge['Anos de Estudo'] != 17]

df_media_escolaridade_por_faixa_etaria = df_sem_registros_de_anos_nao_determinados.groupby(
    'Faixa Etária')['Anos de Estudo'].mean().reset_index()

df_media_escolaridade_por_faixa_etaria.columns = ['Faixa Etária', 'Média de Anos de Estudo']

df_media_escolaridade_por_faixa_etaria


C:\Users\EVERTON\AppData\Local\Temp\ipykernel_8580\1819333857.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_media_escolaridade_por_faixa_etaria = df_sem_registros_de_anos_nao_determinados.groupby(


Faixa Etária  Média de Anos de Estudo
0  20 Anos ou Menos                 8.627477
1      21 a 35 Anos                 9.789356
2      36 a 50 Anos                 8.747839
3      51 a 65 Anos                 7.254205
4   Mais de 65 Anos                 4.833105

3) Qual a UF que concentra a maior renda?


In [10]:
df_ibge['UF'].unique()


array([11, 12, 13, 14, 15, 16, 17, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31,
       32, 33, 35, 41, 42, 43, 50, 51, 52, 53], dtype=int64)

In [11]:
df_ibge['UF'] = df_ibge['UF'].map({   
    11: 'Rondônia',
    12: 'Acre',
    13: 'Amazonas',
    14: 'Roraima',
    15: 'Pará',
    16: 'Amapá',
    17: 'Tocantins',
    21: 'Maranhão',
    22: 'Piauí',
    23: 'Ceará',
    24: 'Rio Grande do Norte',
    25: 'Paraíba',
    26: 'Pernambuco',
    27: 'Alagoas',
    28: 'Sergipe',
    29: 'Bahia',
    31: 'Minas Gerais',
    32: 'Espírito Santo',
    33: 'Rio de Janeiro',
    35: 'São Paulo',
    41: 'Paraná',
    42: 'Santa Catarina',
    43: 'Rio Grande do Sul',
    50: 'Mato Grosso do Sul',
    51: 'Mato Grosso',
    52: 'Goiás',
    53: 'Distrito Federal'
})

df_ibge.head()


UF  Sexo  Idade  Cor  Anos de Estudo  Renda    Altura  Faixa Etária
0  Rondônia     0     23    8              11    800  1.603808  21 a 35 Anos
1  Rondônia     1     23    2              11   1150  1.739790  21 a 35 Anos
2  Rondônia     1     35    8              14    880  1.760444  21 a 35 Anos
3  Rondônia     0     46    2               5   3500  1.783158  36 a 50 Anos
4  Rondônia     1     47    8               8    150  1.690631  36 a 50 Anos

In [12]:
df_renda_por_uf = df_ibge.groupby('UF')['Renda'].sum().reset_index()

uf_com_maior_renda = df_renda_por_uf.loc[df_renda_por_uf['Renda'].idxmax()]

df_uf_com_maior_renda = pd.DataFrame([uf_com_maior_renda])

df_uf_com_maior_renda.columns = ['UF Com a Maior Renda', 'Renda']

df_uf_com_maior_renda


UF Com a Maior Renda     Renda
25            São Paulo  22539969

4) Qual a renda média de pessoas pretas e brancas de homens e mulheres?

In [13]:
df_ibge['Sexo'].unique()


array([0, 1], dtype=int64)

In [14]:
df_ibge['Cor'].unique()


array([8, 2, 4, 6, 0], dtype=int64)

In [15]:
df_ibge['Sexo'] = df_ibge['Sexo'].map({
    0: 'Masculino', 
    1: 'Feminino'
})

df_ibge['Cor'] = df_ibge['Cor'].map({
    0: 'Indígena',
    2: 'Branca',
    4: 'Preta',
    6: 'Amarela',
    8: 'Parda',
    9: 'Sem declaração'
})

df_ibge.head()


UF       Sexo  Idade     Cor  Anos de Estudo  Renda    Altura  \
0  Rondônia  Masculino     23   Parda              11    800  1.603808   
1  Rondônia   Feminino     23  Branca              11   1150  1.739790   
2  Rondônia   Feminino     35   Parda              14    880  1.760444   
3  Rondônia  Masculino     46  Branca               5   3500  1.783158   
4  Rondônia   Feminino     47   Parda               8    150  1.690631   

   Faixa Etária  
0  21 a 35 Anos  
1  21 a 35 Anos  
2  21 a 35 Anos  
3  36 a 50 Anos  
4  36 a 50 Anos

In [16]:
df_brancos_e_pretos = df_ibge[df_ibge['Cor'].isin(['Branca', 'Preta'])]

df_renda_media_pessoas = df_brancos_e_pretos.groupby(['Sexo', 'Cor'])['Renda'].mean().reset_index()

df_renda_media_pessoas.rename(columns={'Renda':'Renda Média'}, inplace=True)

df_renda_media_pessoas


Sexo     Cor  Renda Média
0   Feminino  Branca  2109.866750
1   Feminino   Preta  1134.596400
2  Masculino  Branca  2925.744435
3  Masculino   Preta  1603.861687

5) Qual a renda média concentrada em cada faixa etária?

In [17]:
df_renda_media_por_faixa_etaria = df_ibge.groupby(['Faixa Etária'])['Renda'].mean().reset_index()

df_renda_media_por_faixa_etaria.columns = ['Faixa Etária', 'Renda Média']

df_renda_media_por_faixa_etaria


C:\Users\EVERTON\AppData\Local\Temp\ipykernel_8580\1710618172.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_renda_media_por_faixa_etaria = df_ibge.groupby(['Faixa Etária'])['Renda'].mean().reset_index()


Faixa Etária  Renda Média
0  20 Anos ou Menos   985.348168
1      21 a 35 Anos  1748.286143
2      36 a 50 Anos  2113.756091
3      51 a 65 Anos  2150.196741
4   Mais de 65 Anos  1831.231487

6) Qual a renda média nas faixas de anos de estudo abaixo?
- 2 Anos ou Menos
- 3 a 6 Anos
- 7 a 10 Anos
- 11 a 12 Anos
- 13 Anos ou Mais

In [18]:
bins = [0, 2, 6, 10, 12, np.inf]
labels = ['2 Anos ou Menos', '3 a 6 Anos', '7 a 10 Anos', '11 a 12 Anos', '13 Anos ou Mais']

faixa_anos_de_estudo = pd.cut(df_ibge['Anos de Estudo'], bins=bins, labels=labels)

df_renda_media_por_anos_de_estudo = df_ibge.groupby(faixa_anos_de_estudo)['Renda'].mean().reset_index()

df_renda_media_por_anos_de_estudo.columns = ['Faixa Anos de Estudo', 'Renda Média']

df_renda_media_por_anos_de_estudo


C:\Users\EVERTON\AppData\Local\Temp\ipykernel_8580\2872713848.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_renda_media_por_anos_de_estudo = df_ibge.groupby(faixa_anos_de_estudo)['Renda'].mean().reset_index()


Faixa Anos de Estudo  Renda Média
0      2 Anos ou Menos   828.224420
1           3 a 6 Anos  1149.426648
2          7 a 10 Anos  1403.497163
3         11 a 12 Anos  1869.521910
4      13 Anos ou Mais  4737.374037

7) Qual a escolaridade entre indígenas, para homens e mulheres?

In [19]:
df_ibge['Cor'].unique()


array(['Parda', 'Branca', 'Preta', 'Amarela', 'Indígena'], dtype=object)

In [20]:
df_indigenas = df_ibge[df_ibge['Cor'] == 'Indígena']

df_escolaridade_indigenas = df_indigenas.groupby(['Cor', 'Sexo'])['Anos de Estudo'].mean().reset_index()

df_escolaridade_indigenas.rename(columns={'Anos de Estudo':'Média de Anos de Estudo'}, inplace=True)

df_escolaridade_indigenas


Cor       Sexo  Média de Anos de Estudo
0  Indígena   Feminino                 8.128713
1  Indígena  Masculino                 6.878906

8) Qual a média de anos de estudo entre brancos e negros?

In [21]:
df_escolaridade_brancos_e_pretos = df_brancos_e_pretos.groupby(['Cor'])['Anos de Estudo'].mean().reset_index()

df_escolaridade_brancos_e_pretos.rename(columns={'Anos de Estudo':'Média de Anos de Estudo'}, inplace=True)

df_escolaridade_brancos_e_pretos


Cor  Média de Anos de Estudo
0  Branca                 9.492252
1   Preta                 7.864021

9) Qual a média de anos de estudo e de renda para mulheres brancas e para mulheres negras?

In [22]:
df_mulheres_brancas_e_pretas = df_ibge[(df_ibge['Sexo'] == 'Feminino') & (df_ibge['Cor'].isin(['Branca', 'Preta']))]

df_media_estudo_e_renda_para_mulheres_brancas_e_pretas = df_mulheres_brancas_e_pretas.groupby(
    ['Sexo', 'Cor'])[['Anos de Estudo', 'Renda']].mean().reset_index()

df_media_estudo_e_renda_para_mulheres_brancas_e_pretas.columns = [
    'Sexo', 'Cor', 'Média de Anos de Estudo', 'Renda Média'
]

df_media_estudo_e_renda_para_mulheres_brancas_e_pretas


Sexo     Cor  Média de Anos de Estudo  Renda Média
0  Feminino  Branca                10.300385   2109.86675
1  Feminino   Preta                 8.526480   1134.59640

10) Qual é a UF com maior média de escolaridade e qual a UF com maior média de renda?

In [23]:
df_uf_media_escolaridade_e_renda = df_ibge.groupby(['UF'])[['Anos de Estudo', 'Renda']].mean().reset_index()

df_uf_media_escolaridade_e_renda = df_uf_media_escolaridade_e_renda.loc[
    df_uf_media_escolaridade_e_renda[['Anos de Estudo', 'Renda']].idxmax()]

df_uf_media_escolaridade_e_renda.rename(columns={
    'Anos de Estudo':'Média de Anos de Estudo', 
    'Renda':'Renda Média'
}, inplace=True)

df_uf_media_escolaridade_e_renda.insert(0, 'Descrição', ['Maior Média de Escolaridade', 'Maior Média de Renda'])

df_uf_media_escolaridade_e_renda.reset_index(drop=True, inplace=True)

df_uf_media_escolaridade_e_renda


Descrição                UF  Média de Anos de Estudo  \
0  Maior Média de Escolaridade  Distrito Federal                10.913827   
1         Maior Média de Renda  Distrito Federal                10.913827   

   Renda Média  
0  4241.954722  
1  4241.954722

11) Elabore você uma pergunta sobre a base de dados e escreva o código para responder a pergunta.
- Qual UF possui a maior média de altura entre homens e mulheres?

In [24]:
df_media_altura_por_uf_e_sexo = df_ibge.groupby(['Sexo', 'UF'])[['Altura']].mean().reset_index()

df_maior_media_altura_entre_mulheres = df_media_altura_por_uf_e_sexo.loc[
    [df_media_altura_por_uf_e_sexo[df_media_altura_por_uf_e_sexo['Sexo'] == 'Feminino']['Altura'].idxmax()]]

df_maior_media_altura_entre_homens = df_media_altura_por_uf_e_sexo.loc[
    [df_media_altura_por_uf_e_sexo[df_media_altura_por_uf_e_sexo['Sexo'] == 'Masculino']['Altura'].idxmax()]]

df_uf_maior_media_altura_para_homens_e_mulheres = pd.concat([
    df_maior_media_altura_entre_mulheres, df_maior_media_altura_entre_homens], ignore_index=True)

df_uf_maior_media_altura_para_homens_e_mulheres.columns = ['Sexo', 'UF Com Maior Média de Altura', 'Média de Altura']

df_uf_maior_media_altura_para_homens_e_mulheres


Sexo UF Com Maior Média de Altura  Média de Altura
0   Feminino                    Tocantins         1.703521
1  Masculino                     Rondônia         1.705325